// Help registry — ported from the deleted legacy static/help.js
// (164 entries covering tabs / tiles / charts / columns / filters /
// metrics / calculations / glossary). Schema mirrors the legacy
// entries; the port script lives at /tmp/port-help.mjs in the
// branch history if it needs to be re-run.

export type HelpCategory =
  | "tab"
  | "tile"
  | "chart"
  | "column"
  | "filter"
  | "metric"
  | "calc"
  | "glossary";

export type HelpEntry = {
  id: string;
  category: HelpCategory;
  title: string;
  // One-liner shown in the hover tooltip.
  oneLiner: string;
  // Longer detail rendered in the drawer.
  detail?: string;
  // Optional formula / source / example fields, shown when present.
  formula?: string;
  source?: string;
  example?: string;
  // Cross-links by id — drawer renders these as jump-to chips.
  related?: string[];
};

export const HELP_REGISTRY: HelpEntry[] = [

  // ----- tab -----
  {
    id: "tab.actions",
    category: "tab",
    title: "Actions tab",
    oneLiner: "The flat firehose — every recorded tool-call action, filterable by type.",
    detail: "Each row is one normalised tool call (read_file, run_command, web_fetch, etc.). Use the type dropdown to scope. Pagination caps at 50 rows per page; total count is shown next to the heading.",
    related: ["glossary.action", "filter.action_type"],
  },
  {
    id: "tab.analysis",
    category: "tab",
    title: "Analysis tab",
    oneLiner: "Spending insights for the selected window — headline KPIs, daily trend, top movers, and cost-sensitive signals.",
    detail: "Twelve headline tiles compare this period to the prior period of the same length, including $/M output, cache savings, cache efficacy, high-context turns, $-per-turn, burn rate, top-model concentration, waste, month-to-date, budget MTD, and total sessions. The daily trend has a Model | Project dimension toggle. The 'when you spend' day-of-week × hour-of-day heatmap shows when bills accumulate. Top movers and entrants highlight period-over-period model deltas. Routing efficiency suggestions surface sessions where a cheaper model would have produced equivalent output.",
    related: ["tile.analysis.period_cost", "tile.analysis.mtd", "tile.analysis.cache_savings", "tile.analysis.high_context", "tile.analysis.burn_rate", "chart.analysis_cost_by_hour"],
  },
  {
    id: "tab.compression",
    category: "tab",
    title: "Compression tab",
    oneLiner: "How many tokens and dollars the proxy saved by trimming conversations before forwarding upstream.",
    detail: "Three sections: (1) KPI tiles for tokens saved, $ saved, bytes saved, and turns compressed; (2) a per-day chart showing the savings trajectory; (3) a per-model table breaking down where the savings came from. Bytes are what the proxy can measure directly (it sees the JSON request body before and after the pipeline runs); tokens are derived as bytes ÷ 4 (~Claude tokenizer ratio); dollars value those tokens at the row's model input rate (since the dropped/compressed content is prompt context).",
    related: ["glossary.conversation_compression", "metric.tokens_saved_est", "metric.cost_saved_usd_est", "metric.saved_bytes", "calc.compression_savings", "glossary.marker"],
  },
  {
    id: "tab.cost",
    category: "tab",
    title: "Cost tab",
    oneLiner: "Per-model token consumption and dollar cost over the selected window.",
    detail: "Breaks tokens into the four billable buckets (net input, cache read, cache write/creation, output), shows the cost engine's reliability, and renders a stacked-bar chart of token volume per day. Driven by /api/cost.",
    related: ["metric.net_input", "metric.cache_read", "metric.cache_creation", "metric.output", "metric.cost_usd", "metric.reliability", "calc.token_math"],
  },
  {
    id: "tab.discovery",
    category: "tab",
    title: "Discovery tab",
    oneLiner: "Wasted-effort signals — same-session stale re-reads and repeated no-change command runs.",
    detail: "Two panels: (1) stale re-reads — files the AI client read more than once in a single session after the content changed between reads; (2) repeated commands — commands the AI ran multiple times with no inputs changing in between. Both are proxies for the model losing track of what it already knew.",
    related: ["metric.stale_count", "metric.no_change_reruns", "glossary.freshness"],
  },
  {
    id: "tab.overview",
    category: "tab",
    title: "Overview tab",
    oneLiner: "High-level snapshot — KPI cards, cost & actions over time, top models and tools.",
    detail: "Your first stop. Combines four KPI tiles, two time-series charts (cost and actions per day), and two top-N rollups (models by tokens, tools by action count) for the selected window. Use it to spot whether anything looks off before drilling into a tab.",
    related: ["filter.window", "tab.cost", "tab.tools"],
  },
  {
    id: "tab.patterns",
    category: "tab",
    title: "Patterns tab",
    oneLiner: "Repeatable behaviours the observer noticed across your sessions — the kind you'd want to write down once so future sessions follow the same habit.",
    detail: "Examples in plain English: \"after running `go test`, you usually run `go vet` next\" (a command_pair). \"When working on auth.ts, you also touch login.tsx\" (a cross_tool_file). \"You consistently use the project's `Make build` target instead of raw go build\" (a knowledge_snippet). Each row is one such observation with a confidence score (how sure the observer is it's real, not coincidence) and an observation count (how many independent times it was seen).",
    related: ["column.pattern_type", "metric.confidence", "metric.observation_count"],
  },
  {
    id: "tab.sessions",
    category: "tab",
    title: "Sessions tab",
    oneLiner: "One row per AI-coding session, with project, started time, action count, and (when scored) quality metrics.",
    detail: "A session is one continuous AI-coding conversation in a single tool. Click a row to open the session modal with action breakdown, token buckets, cost, and recent actions. Quality / Errors / Redundancy columns appear only when `observer score` has been run.",
    related: ["glossary.session", "tile.sessions", "metric.quality_score", "metric.error_rate", "metric.redundancy_ratio"],
  },
  {
    id: "tab.tools",
    category: "tab",
    title: "Tools tab",
    oneLiner: "Per-tool aggregates with charts showing when each AI client was active and what kind of work it did.",
    detail: "Four sections: (1) KPI tiles — total actions, distinct tools, overall success rate, busiest tool. (2) Activity over time — stacked area showing per-tool action volume per day. (3) Action-type mix — horizontal stacked bar showing what each tool actually does (read_file vs edit_file vs run_command vs …). (4) The full per-tool table at the bottom.",
    related: ["glossary.tool", "filter.tool", "chart.tools_activity", "chart.tools_breakdown"],
  },
  {
    id: "tab.settings",
    category: "tab",
    title: "Settings tab",
    oneLiner: "Configuration for the observer — editable pricing, backfill jobs, intelligence settings, and read-only TOML viewers.",
    detail: "Three editable sections (Pricing overrides, Backfill, Intelligence) plus read-only viewers for every TOML config section. Pricing edits hot-reload; Backfill jobs poll every 3s while running; Intelligence requires `observer serve` restart to apply. The left rail navigates between sections; the right About-this-section rail can be toggled.",
    related: ["glossary.cost_engine", "metric.reliability"],
  },

  // ----- tile -----
  {
    id: "tile.analysis.burn_rate",
    category: "tile",
    title: "Burn rate $/hr",
    oneLiner: "Dollars spent per hour of active AI usage in the window.",
    detail: "An \"active hour\" is any (date, hour) bucket with at least one turn in the period. This is the user's hourly AI bill while engaged — not a steady-state per-clock-hour rate. Useful for \"my AI assistant costs $X/working-hour\" framing. Active hours are deduplicated across all sessions / projects / models.",
    formula: "period_cost_usd / COUNT(DISTINCT date_hour_bucket) over period",
    related: ["tile.analysis.period_cost", "chart.analysis_cost_by_hour"],
  },
  {
    id: "tile.analysis.cache_efficacy",
    category: "tile",
    title: "Cache efficacy",
    oneLiner: "cache_read share of (cache_read + cache_creation) — how much of your cache traffic is reuse vs setup.",
    detail: "High share = you're reusing cached prompts (good). Low share = you're paying to cache and not getting reuse value back. Color-coded: green ≥80%, amber 50-80%, red below. Paired with Cache savings $ — efficacy is the ratio, savings is the absolute dollar value.",
    formula: "cache_read_tokens / (cache_read_tokens + cache_creation_tokens)",
    related: ["tile.analysis.cache_savings", "metric.cache_read", "metric.cache_creation"],
  },
  {
    id: "tile.analysis.cache_savings",
    category: "tile",
    title: "Cache savings $",
    oneLiner: "Dollar value of cache_read traffic vs uncached (input-rate) pricing.",
    detail: "Counterfactual: per turn, compute the cost if cache_read tokens had been raw input tokens. The diff vs actual cost is the cache savings. Handles LC dispatch correctly because the prompt window (input + cache_read + cache_creation) is invariant under the input ↔ cache_read swap, so the LC tier picks the same rates. Recorded-cost rows are excluded since they can't be decomposed.",
    formula: "savings = Compute(p, {Input += CacheRead, CacheRead = 0}) − Compute(p, bundle), summed per turn over the period",
    related: ["tile.analysis.cache_efficacy", "metric.cache_read", "chart.analysis_cache_savings_trend"],
  },
  {
    id: "tile.analysis.high_context",
    category: "tile",
    title: "High-context turns",
    oneLiner: "Turns whose prompt window exceeded 100K and 200K tokens, with attributed $.",
    detail: "Replaces the prior \"LC tier surcharge\" tile which silently reported $0 for users on models without an LC pricing tier (Anthropic Opus, GPT-5.x non-Pro). Model-agnostic — counts turns purely by prompt window size (input + cache_read + cache_creation). When LC-eligible models (Sonnet 4 / 4.5 / Gemini Pro / GPT-5.4/5.5) actually crossed their tier, the surcharge appears as a sub-line. Otherwise the surcharge is omitted.",
    formula: "turns_over_200k = COUNT(turn) where Input + CacheRead + CacheCreation > 200_000; cost_over_200k_usd = SUM(rowCost) over those turns; lc_surcharge_usd = SUM(rowCost − stripLC(rowStdCost)) only when model has an LC tier",
    related: ["tile.analysis.per_turn", "metric.long_context_tier"],
  },
  {
    id: "tile.analysis.mtd",
    category: "tile",
    title: "Month-to-date",
    oneLiner: "Calendar-month spend so far, with honest prior-month-same-day comparison.",
    detail: "MTD is from month_start to now. The delta sub-line compares to the SAME day-of-month in the prior calendar month (e.g. on May 12, vs Apr 1–12). Linear projection (proj $X) is shown as a reference; the prior-month comparison is the more trustworthy signal because it doesn't assume today's daily rate continues. When MonthlyBudgetUSD is configured, the budget % takes precedence.",
    formula: "mtd = SUM(rowCost) over [month_start, now]; prior_month_same_day = SUM over [prior_month_start, prior_month_start + (now - month_start)]; projection = mtd × days_in_month / days_elapsed",
    related: ["tile.analysis.period_cost", "filter.monthly_budget"],
  },
  {
    id: "tile.analysis.output_rate",
    category: "tile",
    title: "$ /M output (clean rate)",
    oneLiner: "Dollars per million output tokens — the unambiguous per-token-of-value rate.",
    detail: "Replaces the v1.4.49-and-earlier \"Effective rate\" which included cache_write tokens in the denominator. Cache writes are paid-for setup overhead (the bill for stashing context for future reuse), not value tokens — including them artificially lowered the displayed rate when cache churn was high. This tile divides total period cost by output tokens only, mirroring how the industry quotes \"$ /M\".",
    formula: "period_cost_usd × 1_000_000 / period_output_tokens",
    related: ["tile.analysis.cache_savings", "metric.output"],
  },
  {
    id: "tile.analysis.per_turn",
    category: "tile",
    title: "$ per turn (p95)",
    oneLiner: "p95 cost across all costed turns in the window, with mean as sub-line.",
    detail: "Variance signal. A high p95 with low mean means most turns are cheap but a few are very expensive (worth drilling into via Top expensive sessions). A high mean with similar p95 means cost is concentrated across turns broadly. p95 uses ceil(0.95 × N) − 1 as the 0-based index after sorting.",
    formula: "mean_usd = SUM(rowCost) / N; p95_usd = sorted[ceil(0.95 × N) - 1] over turns with rowCost > 0",
    related: ["tile.analysis.period_cost", "chart.analysis_top_sessions"],
  },
  {
    id: "tile.analysis.period_cost",
    category: "tile",
    title: "Spend (period)",
    oneLiner: "Total dollar spend across all models in the selected window.",
    detail: "Per-turn-deduped scan of api_turns + token_usage with the cost engine pricing every row. The delta is vs the prior period of equal length (e.g. last 30 days vs the 30 days before that). Up-vs-prior renders red, down-vs-prior renders green.",
    formula: "SUM(rowCost) over [now - days, now] where rowCost is recorded cost_usd if non-zero, else CostEngine.Compute(model, bundle) per turn",
    related: ["tile.analysis.mtd", "tile.analysis.per_turn", "calc.token_math"],
  },
  {
    id: "tile.analysis.top_model",
    category: "tile",
    title: "Top model by $",
    oneLiner: "Single model that consumed the most spend, with concentration % of period total.",
    detail: "One-glance \"where the money went\" attribution. Concentration % = top model cost / total period cost. High concentration (>70%) means one model dominates; low concentration (<30%) means usage is spread across many models — different cost-management strategies apply.",
    formula: "top_model = argmax(SUM(rowCost) GROUP BY model); concentration_pct = top_model_cost / period_cost × 100",
    related: ["tab.cost"],
  },
  {
    id: "tile.analysis.waste",
    category: "tile",
    title: "Waste $",
    oneLiner: "Stale-read tokens × blended input rate — the dollar cost of re-reading unchanged files.",
    detail: "Discovery flags reads of files that haven't changed since their previous read in the same session. Those tokens are pure waste — the AI re-uploaded context it already had. Priced at the user's blended input rate (weighted across observed models). v1.4.50 calls a thinner WastedTokens helper instead of the full Discovery report so the headline tile doesn't walk the full actions table.",
    formula: "SUM(stale_read_count × file_size_bytes / 4) × blended_input_rate_per_million / 1_000_000",
    related: ["tab.discovery", "metric.net_input"],
  },
  {
    id: "tile.api_turns",
    category: "tile",
    title: "API turns (proxy) tile",
    oneLiner: "Count of HTTP requests captured by the local API proxy.",
    detail: "When you point an AI client at the local proxy via `ANTHROPIC_BASE_URL=http://127.0.0.1:8820` (Claude Code) or `OPENAI_BASE_URL=http://127.0.0.1:8820/v1` (Codex / OpenAI-compatible), the proxy records one row per request in `api_turns`. This is the most accurate token source — it sees the upstream usage envelope directly. Compared to JSONL parsing (next tile) which infers tokens after the fact.",
    formula: "COUNT(*) FROM api_turns",
    related: ["glossary.api_turn", "glossary.proxy_vs_jsonl"],
  },
  {
    id: "tile.failures_24h",
    category: "tile",
    title: "Failures (24h) tile",
    oneLiner: "Action failures in the last 24 hours.",
    detail: "Counts actions with success=false in the last 24h. Click into the Discovery tab if non-zero — repeated failures often correlate with no-change command reruns or stale-context reads.",
    formula: "COUNT(*) FROM actions WHERE success=0 AND timestamp > now-24h",
    related: ["tab.discovery"],
  },
  {
    id: "tile.sessions",
    category: "tile",
    title: "Sessions tile",
    oneLiner: "Total session count in the database (not windowed).",
    detail: "Counts rows in the `sessions` table. The subtitle shows total recorded actions across all sessions. Use the Sessions tab for a windowed view.",
    formula: "COUNT(*) FROM sessions",
    related: ["glossary.session", "tab.sessions"],
  },
  {
    id: "tile.token_rows",
    category: "tile",
    title: "Token rows (jsonl) tile",
    oneLiner: "Count of token-usage events recovered by parsing the AI client's session log.",
    detail: "\"Plentiful but unreliable\" — JSONL parsing recovers token data for every session (no proxy needed) but the AI clients echo cumulative usage on every content block, so the cost engine has to deduplicate. See calc.dedup_a1.",
    formula: "COUNT(*) FROM token_usage",
    related: ["glossary.token_row", "calc.dedup_a1", "glossary.proxy_vs_jsonl"],
  },

  // ----- chart -----
  {
    id: "chart.actions_over_time",
    category: "chart",
    title: "Actions over time chart",
    oneLiner: "Daily action count split by total vs failures.",
    detail: "Line chart bucketed by day. \"Total\" is every recorded action; \"Failures\" is the subset with success=false.",
    source: "/api/timeseries/actions?bucket=day",
  },
  {
    id: "chart.analysis_cache_savings_trend",
    category: "chart",
    title: "Cache savings trend (daily)",
    oneLiner: "Daily $ saved by cache_read traffic vs uncached input pricing.",
    detail: "Per-day version of the Cache savings $ tile. High days are days with heavy cache reuse on Anthropic-pricing models (where cache_read ≈ 0.1× input). Flat or zero days mean either no cache traffic OR all rows were recorded-cost (excluded from this trend since they can't be decomposed).",
    source: "/api/analysis/cache-savings-trend?days=N",
    related: ["tile.analysis.cache_savings", "tile.analysis.cache_efficacy"],
  },
  {
    id: "chart.analysis_cost_by_hour",
    category: "chart",
    title: "Cost by hour of day (UTC)",
    oneLiner: "Bar chart of cost summed per hour-of-day across the window.",
    detail: "Surfaces your daily-rhythm pattern. Buckets are 0..23 in UTC (server-side), so the labels are timezone-stable across restarts. Use it to spot heavy-hour concentrations — e.g. if 80% of your spend is during a 4-hour window, that's when to budget vigilance.",
    source: "/api/analysis/cost-by-hour?days=N",
    related: ["tile.analysis.burn_rate"],
  },
  {
    id: "chart.analysis_movers",
    category: "chart",
    title: "Top movers (period over period)",
    oneLiner: "Top 5 increases and top 5 decreases in $ spend vs prior period of equal length.",
    detail: "Same dim toggle as the trend chart above (model / project / tool). Both increases and decreases are sorted by absolute Δ$. The \"new this period\" table next to it surfaces keys present in the current period but absent from the prior — useful for spotting a new model SKU your client started routing to.",
    source: "/api/analysis/movers?dim=<model|project|tool>&days=N",
    related: ["chart.analysis_trend", "chart.analysis_new_entrants"],
  },
  {
    id: "chart.analysis_new_entrants",
    category: "chart",
    title: "New this period",
    oneLiner: "Keys (model / project / tool) present in the current period but not the prior — sorted by current cost DESC.",
    detail: "Companion to the movers table. New entrants are different from \"increases\" because there's no prior baseline to diff against — they show $ spend only. A high-cost new entrant is often the most impactful signal in a period over period view.",
    source: "/api/analysis/movers?dim=<model|project|tool>&days=N",
    related: ["chart.analysis_movers"],
  },
  {
    id: "chart.analysis_routing",
    category: "chart",
    title: "Routing efficiency suggestions",
    oneLiner: "Conservative \"you could have used a cheaper sibling model\" recommendations.",
    detail: "Intentionally cautious — only flags sessions whose work profile is unambiguously trivial (small prompt, low output, no LC-tier turns, single expensive-model usage), and only one sibling switch per family. Framing is \"could have saved $X\" rather than \"you wasted $X\" because model choice may be deliberate. Per session, not per turn.",
    source: "/api/analysis/routing-suggestions?days=N",
    related: ["chart.analysis_top_sessions"],
  },
  {
    id: "chart.analysis_top_sessions",
    category: "chart",
    title: "Top expensive sessions",
    oneLiner: "Per-session ranking by total $ spend in the window, with explanatory badges.",
    detail: "Aggregates the same per-turn-deduped scan by session_id, ranks by cost DESC. Badges call out why a session landed high: `opus` (any Opus turn), `lc_tier` (any LC-tier turn), `many_turns` (>30), `large_prompt` (>100K single-turn prompt). Click a session to see its full breakdown in the Sessions tab.",
    source: "/api/analysis/top-sessions?days=N&limit=10",
    related: ["tab.sessions", "tile.analysis.per_turn"],
  },
  {
    id: "chart.analysis_trend",
    category: "chart",
    title: "Daily spend (dimension toggle)",
    oneLiner: "Stacked bar of daily $ spend, split by model / project / tool.",
    detail: "One bar per day across the window, segmented by the active dimension. The same dim toggle drives the movers table below so a \"Project\" view shows both daily spend and which projects moved most period-over-period. Reuses the cost engine's GroupByDayModel / GroupByDayProject / GroupByDayTool aggregations so reliability matches /api/cost.",
    source: "/api/analysis/trend?dim=<model|project|tool>&days=N",
    related: ["chart.analysis_movers"],
  },
  {
    id: "chart.compression_by_mechanism",
    category: "chart",
    title: "Savings by mechanism chart",
    oneLiner: "Per-day stacked bar — bytes saved attributed to each compression mechanism (json, code, drop, …).",
    detail: "Reads the compression_events table (one row per individual compression decision, recorded post migration 009). Each segment of the stacked bar is one mechanism: per-content-type compressors (json/code/logs/text/diff/html) plus drop (low-importance message replacements). Stacked height = total bytes saved that day. Days with no compression activity are filtered out.",
    source: "/api/compression/timeseries?bucket=day",
    related: ["glossary.compression_events", "glossary.mechanism-json", "glossary.mechanism-code", "glossary.mechanism-drop"],
  },
  {
    id: "chart.compression_over_time",
    category: "chart",
    title: "Compression savings per day chart",
    oneLiner: "Daily tokens-saved (left axis) and bytes-saved (right axis) from the conversation-compression pipeline.",
    detail: "Line chart bucketed by day. Two y-axes because the units differ by a factor of ~4 (tokens ≈ bytes/4). Each point is the per-day sum of saved tokens / saved bytes across all api_turns that hit the proxy that day. Days with no compression activity are filtered out.",
    source: "/api/timeseries/cost?bucket=day (compression_tokens_saved_est + compression_bytes_saved fields)",
  },
  {
    id: "chart.cost_over_time",
    category: "chart",
    title: "Cost over time chart",
    oneLiner: "Daily token volume, split into the four billable buckets.",
    detail: "Line chart bucketed by day. The four series (Net Input, Cache Read, Cache Write, Output) align with the cost-engine billing buckets. Sums in the meta line above the chart are over the full window.",
    source: "/api/timeseries/cost?bucket=day",
    related: ["metric.net_input", "metric.cache_read", "metric.cache_creation", "metric.output", "calc.token_math"],
  },
  {
    id: "chart.token_volume_by_model",
    category: "chart",
    title: "Token volume per day, split by model (Cost tab)",
    oneLiner: "Stacked bars of daily tokens with each model as its own series — companion view to the bucket-split chart above.",
    detail: "Same per-day axis as the chart above, but each stack is a model rather than a billing bucket. Each bar's height is total tokens (input + output + cache_read + cache_creation summed) attributed to that model on that day. Top-6 models by total tokens get explicit series; everything else rolls up into \"other\" so the legend stays readable.",
    source: "/api/timeseries/tokens-by-model?days=N&project=PATH",
    related: ["chart.token_volume_per_day", "tab.cost", "metric.reliability"],
  },
  {
    id: "chart.token_volume_per_day",
    category: "chart",
    title: "Token volume per day chart (Cost tab)",
    oneLiner: "Stacked bars of daily tokens, split by billing bucket.",
    detail: "Same data as the Overview cost-over-time chart but rendered as bars stacked by bucket. Useful for spotting cache-heavy vs net-input-heavy days at a glance.",
    source: "/api/timeseries/cost?bucket=day",
  },
  {
    id: "chart.tools_activity",
    category: "chart",
    title: "Tools › Activity over time chart",
    oneLiner: "Per-tool action volume per day, stacked area. Top-6 tools shown; remainder rolled into \"other\".",
    detail: "Same data structure as the Top tools chart on Overview. Reuses /api/timeseries/actions's by_tool field, bucketed by day. Each band is one AI client; total height per day = total actions that day.",
    source: "/api/timeseries/actions?bucket=day (by_tool field)",
  },
  {
    id: "chart.tools_breakdown",
    category: "chart",
    title: "Tools › Action-type mix chart",
    oneLiner: "Horizontal stacked bar — one row per tool, segments coloured by action type (read_file / edit_file / run_command / search_text / …).",
    detail: "For each tool in the window, shows what fraction of its actions were each type. Useful for spotting workflow asymmetries: cursor is typically edit-heavy, claude-code is typically a mix, codex is typically run-command-heavy. A tool with an unexpected mix (e.g. claude-code suddenly 90% search) usually means a session-design change.",
    source: "/api/tools/breakdown?days=N",
  },
  {
    id: "chart.top_models",
    category: "chart",
    title: "Top models (by tokens) chart",
    oneLiner: "Top 8 models in the window, ranked by total tokens consumed.",
    detail: "Stacked bar — Net Input + Cache Read + Output per model. Cache Write omitted to keep the chart legible (most traffic is read-heavy).",
    source: "/api/models",
  },
  {
    id: "chart.top_tools",
    category: "chart",
    title: "Top tools chart (actions over time)",
    oneLiner: "Per-day action counts per AI client, stacked. Top-6 tools shown explicitly; the rest roll into \"other\".",
    detail: "Stacked-area time series. Each band is one AI client (claude-code, cursor, codex, …). Use it to see *when* each tool was active, not just the aggregate ranking — patterns like \"cursor only on weekdays\" or \"claude-code spike when refactoring\" pop out here.",
    source: "/api/timeseries/actions?bucket=day (by_tool field)",
  },

  // ----- column -----
  {
    id: "column.actions.error",
    category: "column",
    title: "Actions › Error",
    oneLiner: "Truncated error message when success=false.",
  },
  {
    id: "column.actions.ok",
    category: "column",
    title: "Actions › OK",
    oneLiner: "✓ for success, ✗ for failure.",
  },
  {
    id: "column.actions.session",
    category: "column",
    title: "Actions › Session",
    oneLiner: "Owning session ID (truncated).",
  },
  {
    id: "column.actions.target",
    category: "column",
    title: "Actions › Target",
    oneLiner: "File path / command / URL the action operated on.",
  },
  {
    id: "column.actions.tool",
    category: "column",
    title: "Actions › Tool",
    oneLiner: "AI client that executed the action.",
  },
  {
    id: "column.actions.tool_name",
    category: "column",
    title: "Actions › Tool name",
    oneLiner: "The raw tool name as the AI client emitted it (before normalisation).",
  },
  {
    id: "column.actions.type",
    category: "column",
    title: "Actions › Type",
    oneLiner: "Normalised action type (read_file, run_command, web_fetch, ...).",
  },
  {
    id: "column.actions.when",
    category: "column",
    title: "Actions › When",
    oneLiner: "Wall-clock timestamp of the action.",
  },
  {
    id: "column.compression.compressed",
    category: "column",
    title: "Compression › Compressed",
    oneLiner: "Post-compression conversation payload size in bytes (what the proxy actually sent upstream).",
  },
  {
    id: "column.compression.dropped",
    category: "column",
    title: "Compression › Dropped",
    oneLiner: "Count of blocks dropped entirely (replaced by a marker).",
    related: ["glossary.marker"],
  },
  {
    id: "column.compression.markers",
    category: "column",
    title: "Compression › Markers",
    oneLiner: "Count of compression markers inserted into the conversation.",
    related: ["glossary.marker"],
  },
  {
    id: "column.compression.model",
    category: "column",
    title: "Compression › Model",
    oneLiner: "Upstream model ID this row aggregates.",
  },
  {
    id: "column.compression.original",
    category: "column",
    title: "Compression › Original",
    oneLiner: "Pre-compression conversation payload size in bytes.",
  },
  {
    id: "column.compression.saved",
    category: "column",
    title: "Compression › Saved",
    oneLiner: "Bytes saved (original − compressed). Negative = compression added overhead, flagged red.",
    related: ["metric.saved_bytes"],
  },
  {
    id: "column.compression.saved_pct",
    category: "column",
    title: "Compression › Saved %",
    oneLiner: "Saved bytes as a percentage of original.",
    formula: "(original - compressed) / original",
  },
  {
    id: "column.compression.tool_results",
    category: "column",
    title: "Compression › Tool results",
    oneLiner: "Count of tool_result blocks the pipeline compressed in-place.",
  },
  {
    id: "column.compression.turns",
    category: "column",
    title: "Compression › Turns",
    oneLiner: "Number of API turns this row covers.",
  },
  {
    id: "column.cost.cache_r",
    category: "column",
    title: "Cost › Cache R",
    oneLiner: "Cache-read tokens — prompt tokens served from Anthropic's ephemeral cache.",
    detail: "Billed at the cache-read rate (~10% of standard input rate).",
    related: ["metric.cache_read"],
  },
  {
    id: "column.cost.cache_w",
    category: "column",
    title: "Cost › Cache W",
    oneLiner: "Cache-write/creation tokens — new tokens written to the ephemeral cache.",
    detail: "Billed at 1.25× (5m tier) or 2× (1h tier) of standard input rate. Anthropic only — Codex/OpenAI billing has no equivalent.",
    related: ["metric.cache_creation"],
  },
  {
    id: "column.cost.cost",
    category: "column",
    title: "Cost › Cost",
    oneLiner: "Computed dollar cost for this row. Always derived from token counts × the model's pricing entry — neither Anthropic nor OpenAI returns cost_usd in their API responses.",
    detail: "For api_turns rows (proxy): tokens × pricing-table[model]. For token_usage rows from OpenCode and Pi (which compute cost client-side and write it into their JSONL): the recorded estimated_cost_usd is used as-is. Every other JSONL adapter goes through the same tokens × pricing path. Pricing-table source-of-truth: docs/pricing-reference.md.",
    related: ["calc.cost_math", "glossary.cost_provenance"],
  },
  {
    id: "column.cost.model",
    category: "column",
    title: "Cost › Model",
    oneLiner: "Model identifier (claude-opus-4-5, gpt-4o, etc.).",
    detail: "Comes from the upstream usage envelope (proxy) or the JSONL `message.model` field. Models without pricing data render with reliability=unreliable.",
  },
  {
    id: "column.cost.net_in",
    category: "column",
    title: "Cost › Net In",
    oneLiner: "Net input tokens — fresh prompt tokens, cache hits subtracted.",
    detail: "Billed at the model's standard input rate.",
    related: ["metric.net_input", "calc.token_math"],
  },
  {
    id: "column.cost.output",
    category: "column",
    title: "Cost › Output",
    oneLiner: "Output tokens — what the model generated.",
    detail: "Billed at the model's output rate (typically 5× input).",
    related: ["metric.output"],
  },
  {
    id: "column.cost.reliab",
    category: "column",
    title: "Cost › Reliab.",
    oneLiner: "Trust level for this row's tokens — accurate / approximate / unreliable / unknown — plus a \"~\" suffix when pricing was inferred via family-prefix fallback.",
    detail: "Token-side reliability: accurate = proxy-captured (provider usage envelope verbatim); approximate = JSONL-captured but the client recorded the provider's usage envelope intact; unreliable = JSONL streaming-time placeholders (Claude Code, ~10% off output); unknown = no pricing-table entry. Pricing-side: if the value carries a \"~\", the rate came from a family-prefix fallback (e.g. claude-opus-4-99 inheriting claude-opus-4 family rates) rather than an exact-match table entry — hover the tilde for details. Pricing source-of-truth: docs/pricing-reference.md.",
    related: ["metric.reliability", "glossary.cost_provenance"],
  },
  {
    id: "column.cost.source",
    category: "column",
    title: "Cost › Source",
    oneLiner: "Where the token data underneath this row came from: proxy, jsonl, or mixed.",
    detail: "proxy = the local API proxy intercepted the upstream request and read the usage envelope directly (one row per HTTP request, no dedup needed). jsonl = recovered by parsing the AI client's on-disk session log (works without configuring a base URL but the client echoes cumulative usage on every content block, so the cost engine deduplicates). mixed = both sources contributed rows that survived dedup.",
    related: ["glossary.proxy_vs_jsonl", "metric.reliability"],
  },
  {
    id: "column.cost.turns",
    category: "column",
    title: "Cost › Turns",
    oneLiner: "Number of API turns (proxy) or token-row groups (jsonl) rolled into this row.",
    detail: "When grouped by model, this is the count of turns attributed to that model in the window.",
  },
  {
    id: "column.discover.command",
    category: "column",
    title: "Discovery › Command",
    oneLiner: "Command string (truncated). Repeated-commands section.",
  },
  {
    id: "column.discover.failed",
    category: "column",
    title: "Discovery › Failed",
    oneLiner: "How many runs failed (non-zero exit code).",
  },
  {
    id: "column.discover.file",
    category: "column",
    title: "Discovery › File",
    oneLiner: "File path (truncated). Stale-rereads section.",
  },
  {
    id: "column.discover.no_change_reruns",
    category: "column",
    title: "Discovery › No-change reruns",
    oneLiner: "Re-runs of the same command with no relevant inputs changed in between.",
    detail: "Heuristic — checks whether any file the command's output referenced was modified between runs.",
    related: ["metric.no_change_reruns"],
  },
  {
    id: "column.discover.reads",
    category: "column",
    title: "Discovery › Reads",
    oneLiner: "Total reads of this file in the window.",
  },
  {
    id: "column.discover.runs",
    category: "column",
    title: "Discovery › Runs",
    oneLiner: "Total times this command was run in the window.",
  },
  {
    id: "column.discover.stale",
    category: "column",
    title: "Discovery › Stale",
    oneLiner: "Same-session re-reads of a file after it changed.",
    detail: "The freshness engine tags each read with fresh / stale / missing / unknown by hashing file content. A read is counted as \"stale\" here only when the SAME session previously read the file and the content changed between the two reads. Cross-session reads are filtered out at query time — a session that has just started has no memory of what a prior session saw, so flagging it as \"stale\" would imply waste that didn't happen.",
    related: ["metric.stale_count", "glossary.freshness", "calc.freshness_classification"],
  },
  {
    id: "column.discover.wasted",
    category: "column",
    title: "Discovery › Est. wasted tokens",
    oneLiner: "Estimated prompt tokens spent re-ingesting content the session already had.",
    detail: "Calculated as stale_count × ceil(file_size_bytes / 4). The /4 ratio comes from Claude's tokenizer averaging ~4 characters per token on typical source code. When file size isn't known (e.g. file deleted before file_state was populated), falls back to 512 tokens per read (assumes a 2 KB excerpt). Treat the absolute number as an upper-bound order-of-magnitude estimate, not exact.",
    formula: "stale_count × ceil(file_size_bytes / 4)",
  },
  {
    id: "column.patterns.confidence",
    category: "column",
    title: "Patterns › Confidence",
    oneLiner: "Decay-weighted confidence score (0–1). Older observations weigh less.",
  },
  {
    id: "column.patterns.data",
    category: "column",
    title: "Patterns › Data",
    oneLiner: "Pattern payload (shape varies by type) — rendered as key=value pairs.",
  },
  {
    id: "column.patterns.observations",
    category: "column",
    title: "Patterns › Observations",
    oneLiner: "Raw count of observations supporting this pattern.",
  },
  {
    id: "column.patterns.type",
    category: "column",
    title: "Patterns › Type",
    oneLiner: "Pattern category — knowledge_snippet, command_pair, cross_tool_file, etc.",
  },
  {
    id: "column.sessions.actions",
    category: "column",
    title: "Sessions › Actions",
    oneLiner: "Total recorded actions in the session.",
    formula: "COUNT(*) FROM actions WHERE session_id = s.id",
  },
  {
    id: "column.sessions.cache_creation_tokens",
    category: "column",
    title: "Sessions › Cache W",
    oneLiner: "Cache-write tokens (1.25× input rate on Anthropic) — tokens paid to stash context for future reuse.",
    detail: "Cache writes are the cost of setting up future cache reads. High Cache W with low Cache R signals wasted setup (session ended before reuse paid off). Healthy ratio is Cache R ≫ Cache W.",
    related: ["column.sessions.cache_read_tokens", "tile.analysis.cache_efficacy", "metric.cache_creation"],
  },
  {
    id: "column.sessions.cache_read_tokens",
    category: "column",
    title: "Sessions › Cache R",
    oneLiner: "Cache-read tokens (~0.1× input rate on Anthropic) — prompt tokens served from cache instead of resubmitted.",
    detail: "High Cache R relative to Input means the session is reusing context efficiently. The Analysis tab's Cache savings $ tile quantifies this in dollars across the whole window.",
    related: ["column.sessions.cache_creation_tokens", "tile.analysis.cache_savings", "metric.cache_read"],
  },
  {
    id: "column.sessions.cost",
    category: "column",
    title: "Sessions › Cost",
    oneLiner: "Computed dollar cost for this session. A trailing \"~\" means the figure is approximate (JSONL-derived, not billing-grade).",
    detail: "Same cost engine as the Cost tab. The \"~\" suffix marks rows whose Reliability tag is anything other than \"accurate\" — typically because the session went through a non-proxied AI client. Hover the value to see the reliability tag. Sessions whose AI client never produced a token row render \"—\".",
    related: ["column.sessions.tokens", "column.cost.cost", "column.cost.reliab", "glossary.proxy_vs_jsonl"],
  },
  {
    id: "column.sessions.elapsed",
    category: "column",
    title: "Sessions › Elapsed",
    oneLiner: "Time from session start to last activity (last action or ended_at).",
    detail: "Computed as COALESCE(ended_at, MAX(actions.timestamp)) − started_at. Open sessions (no ended_at) still show their in-flight elapsed time using the most recent action. Rendered with the two largest non-zero units (\"2h 15m\", \"1d 4h\", \"35m 12s\").",
    formula: "last_seen_at − started_at, where last_seen_at = COALESCE(s.ended_at, MAX(a.timestamp))",
    related: ["column.sessions.started"],
  },
  {
    id: "column.sessions.errors",
    category: "column",
    title: "Sessions › Errors",
    oneLiner: "Action failure rate for this session.",
    formula: "failures / total_actions",
    related: ["metric.error_rate"],
  },
  {
    id: "column.sessions.id",
    category: "column",
    title: "Sessions › ID",
    oneLiner: "Stable session identifier (truncated for display).",
    detail: "Click the row to open the session detail modal.",
  },
  {
    id: "column.sessions.input_tokens",
    category: "column",
    title: "Sessions › Input",
    oneLiner: "Net input tokens for this session (excludes cache hits).",
    detail: "Raw prompt tokens that bill at the model's input rate. Sourced from the cost engine's GroupBySession rollup with SourceAuto dedup. v1.4.51 split the prior single \"Tokens\" column into its four billable buckets so users can see the cache-read vs raw-input split at a glance.",
    related: ["column.sessions.cache_read_tokens", "column.sessions.cache_creation_tokens", "column.sessions.output_tokens", "metric.net_input"],
  },
  {
    id: "column.sessions.output_tokens",
    category: "column",
    title: "Sessions › Output",
    oneLiner: "Tokens the model generated for this session — the bottom-line \"value\" tokens.",
    detail: "Pairs with the Analysis tab's $/M output tile. Output tokens are the unambiguous value generated per dollar; cache traffic is overhead/reuse setup.",
    related: ["tile.analysis.output_rate", "metric.output"],
  },
  {
    id: "column.sessions.project",
    category: "column",
    title: "Sessions › Project",
    oneLiner: "Working-directory root at session start (last two path segments shown; full path on hover).",
    related: ["glossary.project"],
  },
  {
    id: "column.sessions.quality",
    category: "column",
    title: "Sessions › Quality",
    oneLiner: "Composite session quality score (0–1, higher is better). Populated by `observer score`.",
    related: ["metric.quality_score"],
  },
  {
    id: "column.sessions.redundancy",
    category: "column",
    title: "Sessions › Redundancy",
    oneLiner: "Fraction of actions classified as redundant (stale rereads, no-change reruns, etc.).",
    related: ["metric.redundancy_ratio"],
  },
  {
    id: "column.sessions.started",
    category: "column",
    title: "Sessions › Started",
    oneLiner: "Wall-clock timestamp of the first action in the session.",
  },
  {
    id: "column.sessions.tokens",
    category: "column",
    title: "Sessions › Total tokens (deprecated — split into Input/Cache R/Cache W/Output as of v1.4.51)",
    oneLiner: "Sum of all four billable buckets. Still emitted in the JSON for back-compat; no longer rendered as a column.",
    formula: "Input + Output + CacheRead + CacheCreation",
    related: ["column.sessions.input_tokens", "column.sessions.output_tokens", "column.sessions.cache_read_tokens", "column.sessions.cache_creation_tokens"],
  },
  {
    id: "column.sessions.tool",
    category: "column",
    title: "Sessions › Tool",
    oneLiner: "Which AI client this session ran in.",
    related: ["glossary.tool"],
  },
  {
    id: "column.tools.actions",
    category: "column",
    title: "Tools › Actions",
    oneLiner: "Total actions recorded for this tool in the window.",
  },
  {
    id: "column.tools.failures",
    category: "column",
    title: "Tools › Failures",
    oneLiner: "Subset of actions with success=false.",
  },
  {
    id: "column.tools.first_seen",
    category: "column",
    title: "Tools › First seen",
    oneLiner: "Earliest action timestamp for this tool in the window.",
  },
  {
    id: "column.tools.last_seen",
    category: "column",
    title: "Tools › Last seen",
    oneLiner: "Most recent action timestamp for this tool in the window.",
  },
  {
    id: "column.tools.sessions",
    category: "column",
    title: "Tools › Sessions",
    oneLiner: "Distinct session count this tool appeared in (in window).",
  },
  {
    id: "column.tools.success_rate",
    category: "column",
    title: "Tools › Success rate",
    oneLiner: "Successful actions as a percentage of total.",
    formula: "1 - (failures / actions)",
    related: ["metric.success_rate"],
  },
  {
    id: "column.tools.tool",
    category: "column",
    title: "Tools › Tool",
    oneLiner: "AI client name.",
  },

  // ----- filter -----
  {
    id: "filter.action_type",
    category: "filter",
    title: "Action-type filter (Actions tab)",
    oneLiner: "Scope the actions firehose to one normalised type (read_file, run_command, etc.).",
    detail: "Action types are normalised across all adapters (claude-code, cursor, codex, cline, copilot) so a `read_file` from any tool means the same thing.",
    related: ["glossary.action"],
  },
  {
    id: "filter.project",
    category: "filter",
    title: "Project filter",
    oneLiner: "Restrict views to sessions/actions whose project root matches.",
    detail: "Project roots are derived from the working directory at session start (with `/.git/...` paths folded back to the working-tree root). Selecting a project re-fires the current tab.",
    related: ["glossary.project"],
  },
  {
    id: "filter.tool",
    category: "filter",
    title: "Tool filter",
    oneLiner: "Restrict views to one AI client (claude-code / cursor / codex / etc.). Default: all.",
    detail: "Populated from the per-tool last-seen list. Selecting a tool re-fires whatever tab is active.",
    related: ["glossary.tool"],
  },
  {
    id: "filter.window",
    category: "filter",
    title: "Window selector",
    oneLiner: "Time horizon — 7 / 30 / 90 / 365 days from now.",
    detail: "Every loadable view honours this filter via a `days=` query param. Charts bucket by day; tables include all rows whose timestamp falls in [now - days, now].",
  },

  // ----- metric -----
  {
    id: "glossary.retrieve_rate",
    category: "metric",
    title: "CCR retrieve rate",
    oneLiner: "Fraction of stashed tool_result bodies that the model later actually retrieved via the retrieve_stashed MCP tool.",
    detail: "When a tool_result body exceeds the inline-size threshold (default 8 KB), the proxy stashes it to `~/.observer/stash/<sha>` and replaces it inline with a marker. The model retrieves originals on-demand via `retrieve_stashed({sha})`. Retrieve rate = `retrieve_stashed signals ÷ stash events` over the window. Higher than 100% means the same sha was retrieved multiple times (good signal: the body was load-bearing enough to come back to).",
    related: ["glossary.mechanism-stash"],
  },
  {
    id: "glossary.rolling_cost_net",
    category: "metric",
    title: "Rolling-summarisation net cost",
    oneLiner: "Cache-creation savings from rolling_summary minus the Haiku call cost — positive means rolling-summ is paying its way.",
    detail: "D20 rolling summarisation calls Anthropic Haiku to produce summaries of older messages. Those calls cost money. The `rolling_summary` mechanism saves bytes that would otherwise be `cache_creation` tokens on the next turn (the conversation prefix grew past Anthropic's prompt-cache window). Net delta = (saved bytes ÷ 4 × cache_creation rate) − (Haiku spend). Positive = rolling-summ is paying its way; negative = Haiku exceeds savings on this workload.",
    related: ["glossary.mechanism-rolling_summary"],
  },
  {
    id: "metric.action_count",
    category: "metric",
    title: "Action count",
    oneLiner: "Total actions recorded.",
  },
  {
    id: "metric.cache_creation",
    category: "metric",
    title: "Cache Write / Creation tokens",
    oneLiner: "Tokens written to the ephemeral cache. Billed at 1.25× (5m tier) or 2× (1h tier) of input rate.",
    detail: "Caching is opt-in via cache_control on prompt blocks. The proxy splits totals into 5m vs 1h tiers (`cache_creation_1h_tokens` is the 1h subset; `cache_creation_tokens − cache_creation_1h_tokens` is the 5m portion).",
    source: "api_turns.cache_creation_tokens, api_turns.cache_creation_1h_tokens",
    related: ["glossary.cache_5m_vs_1h", "metric.cache_read"],
  },
  {
    id: "metric.cache_read",
    category: "metric",
    title: "Cache Read tokens",
    oneLiner: "Prompt tokens served from Anthropic's ephemeral cache, billed at ~10% of input rate.",
    detail: "When the model can replay cached prompt prefixes, those tokens come at a steep discount. The cost engine treats this as its own line item.",
    source: "api_turns.cache_read_tokens",
    related: ["metric.cache_creation", "glossary.cache_5m_vs_1h"],
  },
  {
    id: "metric.confidence",
    category: "metric",
    title: "Confidence (patterns)",
    oneLiner: "How sure the observer is that this pattern is a real, repeatable behaviour vs a coincidence — 0 to 1.",
    detail: "Each pattern (knowledge_snippet, command_pair, cross_tool_file, …) is assembled from one or more observations across sessions. Confidence is a weighted score that goes UP with more independent observations and stays high when those observations are recent, but DECAYS over time so a pattern that hasn't been seen in months gradually drops out. Below ~0.3 the pattern is \"we saw it once, take with a grain of salt\"; above ~0.7 it's \"this is the model's actual habit.\"",
    related: ["column.pattern_type", "metric.observation_count"],
  },
  {
    id: "metric.cost_saved_usd_est",
    category: "metric",
    title: "Dollars saved (est.)",
    oneLiner: "Estimated USD value of the tokens compression spared. Signed.",
    detail: "For each row: tokens_saved_est × the row's model input rate (per million tokens, from the cost engine pricing table). Aggregates by sum across rows. Uses the *input* rate (not output, not cache) because compression operates on prompt context — dropped/truncated content would have been billed as fresh input on the upstream side.",
    formula: "cost_saved_usd_est = Σ_rows (tokens_saved_est × pricing.input ÷ 1,000,000)",
    related: ["metric.tokens_saved_est", "calc.cost_math"],
  },
  {
    id: "metric.cost_usd",
    category: "metric",
    title: "Cost (USD)",
    oneLiner: "Estimated dollar cost — what this row of activity would bill you for.",
    detail: "Preference order: (1) the upstream API's self-reported cost_usd field if present (the proxy passes this through verbatim — gold standard, reliability=high); (2) tokens × the model's pricing entry, summed across the four buckets (net input × input rate, cache_read × cache_read rate, cache_creation_5m × cache_creation rate, cache_creation_1h × cache_creation_1h rate, output × output rate). When the model isn't in our pricing table, cost shows $0.0000 and reliability flips to unreliable — token counts are still real, the dollar number just isn't computable.",
    related: ["calc.cost_math", "metric.reliability", "column.cost.source"],
  },
  {
    id: "metric.error_rate",
    category: "metric",
    title: "Error rate",
    oneLiner: "Fraction of a session's actions that failed (success=false). 0 = clean, 1 = nothing worked.",
    detail: "Computed at score time as failures / total_actions per session. \"Failure\" here is the binary success column on each action: a non-zero exit code on a command, an error response from a tool call, an exception during file ops. Hover failures column on the Actions tab for examples.",
  },
  {
    id: "metric.est_wasted_tokens",
    category: "metric",
    title: "Estimated wasted tokens",
    oneLiner: "Tokens spent on stale rereads, calculated as stale_count × ceil(file_size / 4).",
  },
  {
    id: "metric.failure_count",
    category: "metric",
    title: "Failure count",
    oneLiner: "Actions with success=false.",
  },
  {
    id: "metric.net_input",
    category: "metric",
    title: "Net Input tokens",
    oneLiner: "Fresh prompt tokens billed at the standard input rate (cache hits subtracted).",
    detail: "When Anthropic prompt-caching is in play, the upstream usage envelope reports total input split across three buckets: net input (fresh), cache read (cache hit), and cache creation (new cache write). \"Net Input\" is the fresh portion only.",
    formula: "net_input = usage.input_tokens (already net of cache hits in Anthropic's envelope)",
    source: "api_turns.input_tokens (proxy) | token_usage.input_tokens (jsonl)",
    related: ["metric.cache_read", "metric.cache_creation", "calc.token_math"],
  },
  {
    id: "metric.no_change_reruns",
    category: "metric",
    title: "No-change reruns",
    oneLiner: "Re-runs of a command where no relevant inputs changed between runs.",
  },
  {
    id: "metric.observation_count",
    category: "metric",
    title: "Observation count",
    oneLiner: "How many independent observations supported this pattern.",
  },
  {
    id: "metric.output",
    category: "metric",
    title: "Output tokens",
    oneLiner: "Tokens the model generated. Billed at the model's output rate (typically 5× input).",
    source: "api_turns.output_tokens | token_usage.output_tokens",
  },
  {
    id: "metric.quality_score",
    category: "metric",
    title: "Quality score",
    oneLiner: "Single 0–1 signal of how well a session went. Higher is better.",
    detail: "Composite produced by `observer score`: blends success rate (more weight), redundancy ratio (penalises stale rereads + no-change reruns), freshness signal (penalises sessions that re-read the same files repeatedly), and a small length normaliser (very short sessions don't score well even if perfect — not enough signal). Above 0.7 is solid; below 0.4 something went wrong. Only populated for sessions where `observer score` has been run.",
    related: ["metric.error_rate", "metric.redundancy_ratio"],
  },
  {
    id: "metric.redundancy_ratio",
    category: "metric",
    title: "Redundancy ratio",
    oneLiner: "Fraction of a session's actions that were redundant — stale rereads or no-change reruns.",
    detail: "Computed at score time as (stale_reread_count + no_change_rerun_count) / total_actions. Both numerator components are scoped per-session for the same reason stale_count is.",
  },
  {
    id: "metric.reliability",
    category: "metric",
    title: "Reliability",
    oneLiner: "How much you should trust the cost number on this row — high / medium / low / unreliable.",
    detail: "high = the upstream API itself reported the cost (proxy captured it directly from the response envelope; this is ground truth). medium = computed by multiplying tokens × the model's pricing entry from the cost engine; correct as long as our pricing table is current. low = at least one bucket was estimated (e.g. cache_creation tier split inferred from totals). unreliable = no pricing entry for this model — cost shows $0.0000 but tokens are still counted.",
    related: ["metric.cost_usd", "calc.cost_math"],
  },
  {
    id: "metric.saved_bytes",
    category: "metric",
    title: "Saved bytes",
    oneLiner: "Bytes saved by compression. Negative = compression made it bigger (flagged red).",
  },
  {
    id: "metric.saved_pct",
    category: "metric",
    title: "Saved %",
    oneLiner: "Saved bytes as a fraction of the original.",
  },
  {
    id: "metric.scored_count",
    category: "metric",
    title: "Scored count",
    oneLiner: "How many sessions in the current filter have been scored by `observer score`.",
  },
  {
    id: "metric.stale_count",
    category: "metric",
    title: "Stale count",
    oneLiner: "Number of in-session re-reads that hit a changed version of the file. Cross-session reads are NOT counted.",
    detail: "Per-file count of \"stale\" reads scoped to a single session. The freshness engine classifies a read as stale when the file's content hash differs from a previous read — but the stale-count metric only counts those where the previous read also belongs to the same session. A read in session B that lands on a file last touched by session A is treated as a fresh look (it is, from session B's perspective), not a stale rediscovery. WHAT THE SYSTEM DOES with this signal: detection and reporting only — the observer surfaces it on the dashboard so YOU can decide what to change. It does not block, cache, or rewrite the read in flight.",
    related: ["glossary.freshness", "calc.freshness_classification", "column.discover.wasted", "glossary.sidechain"],
  },
  {
    id: "metric.success_rate",
    category: "metric",
    title: "Success rate",
    oneLiner: "Fraction of actions that succeeded.",
    formula: "1 - (failures / total)",
  },
  {
    id: "metric.tokens_saved_est",
    category: "metric",
    title: "Tokens saved (est.)",
    oneLiner: "Estimated input tokens spared by conversation compression. Signed — can be negative.",
    detail: "Computed as saved_bytes ÷ 4 per row, then summed. The ÷4 ratio comes from Anthropic's tokenizer averaging ~4 chars per token on typical English/code; for prose-heavy or highly-repetitive content it can drift to 3–5. This is the right ballpark unit for \"how much did compression help?\" because tokens are what cost dollars; bytes are just what the proxy can see.",
    formula: "tokens_saved_est = (original_bytes − compressed_bytes) ÷ 4",
    related: ["metric.cost_saved_usd_est", "metric.saved_bytes", "calc.compression_savings"],
  },
  {
    id: "metric.total_actions",
    category: "metric",
    title: "Total actions (per session)",
    oneLiner: "Recomputed live as COUNT(*) FROM actions WHERE session_id = s.id (the stored column was historically zero).",
  },
  {
    id: "metric.turn_count",
    category: "metric",
    title: "Turn count",
    oneLiner: "Number of API turns rolled into a row.",
  },

  // ----- calc -----
  {
    id: "calc.compression_savings",
    category: "calc",
    title: "Compression savings",
    oneLiner: "How saved bytes/% are calculated.",
    detail: "Per turn: original_bytes is the JSON-encoded conversation payload before the pipeline ran. compressed_bytes is what the proxy actually forwarded upstream. saved = original − compressed. Negative savings happen when payloads are small enough that marker overhead dominates — flagged red.",
    related: ["metric.saved_bytes", "metric.saved_pct", "glossary.marker"],
  },
  {
    id: "calc.cost_math",
    category: "calc",
    title: "Cost math",
    oneLiner: "How tokens become dollars — the per-bucket pricing × tokens formula.",
    detail: "For each row: cost_usd = (net_input × p.input + cache_read × p.cache_read + cache_creation_5m × p.cache_creation + cache_creation_1h × p.cache_creation_1h + output × p.output) ÷ 1,000,000. All rates are USD per 1M tokens. The 5m vs 1h split for cache_creation: cache_creation_1h is the 1h-tier portion (priced at 2× the 5m rate); the rest (cache_creation_total − cache_creation_1h) is the 5m portion. Pricing comes from internal/intelligence/cost/pricing_default.go (baked-in defaults) plus any user overrides from observer config. When the upstream API itself reports cost_usd in the response envelope (proxy-sourced rows), that value is preferred over the computed one — gold standard.",
    formula: "cost_usd = Σ_buckets (tokens_in_bucket × rate_per_M ÷ 1e6)",
    related: ["metric.cost_usd", "metric.reliability", "glossary.cache_5m_vs_1h", "calc.token_math"],
  },
  {
    id: "calc.dedup_a1",
    category: "calc",
    title: "JSONL dedup (audit item A1)",
    oneLiner: "Why we drop duplicate token-usage rows before computing cost.",
    detail: "When an AI client makes one upstream API call that produces N content blocks (e.g. a turn with text + 3 tool calls = 4 blocks), the client writes N JSONL log lines, and each line carries the SAME cumulative usage envelope from the response. If you summed naively, that one API call would count 2-4× in the totals. Two layers of dedup catch this: (1) the Claude Code adapter dedupes on Anthropic's `message.id` at write time, so new rows are clean; (2) the cost engine adds defence-in-depth dedup at rollup time on (source_file, model, timestamp-bucketed-to-minute, input, output, cache_read, cache_creation) so any pre-A1 historical rows that slipped through still get collapsed. Migration 007 ran a one-time pass that collapsed ~47% of pre-fix rows in the live install.",
    related: ["glossary.token_row", "glossary.proxy_vs_jsonl"],
  },
  {
    id: "calc.freshness_classification",
    category: "calc",
    title: "Freshness classification",
    oneLiner: "How a file read is tagged fresh / stale / missing / etc.",
    detail: "The freshness engine hashes file content at read time and stores the hash in `file_state` keyed by (project, file). On the next read in the same session: if the hash matches → fresh; if it differs (file edited since last read) → stale; if file doesn't exist anymore → missing. Cross-session reads start fresh — no comparison happens against another session's history.",
    related: ["metric.stale_count", "glossary.freshness"],
  },
  {
    id: "calc.token_math",
    category: "calc",
    title: "Token math",
    oneLiner: "How Anthropic's four-bucket usage envelope composes into the numbers you see.",
    detail: "The Anthropic API returns four numbers per request: input_tokens (the prompt content NOT served from cache — already net), cache_read_input_tokens (prompt content served from the ephemeral cache), cache_creation_input_tokens (prompt content newly written to the cache), and output_tokens (what the model generated). The dashboard treats all four as separate buckets because they bill at very different rates: cache_read ≈ 0.1× input, cache_creation ≈ 1.25× input (5m tier) or 2× input (1h tier), output ≈ 5× input. Total prompt context sent for a turn = input + cache_read + cache_creation. Total tokens billed = those three + output.",
    formula: "prompt_context = net_input + cache_read + cache_creation     |     total = prompt_context + output",
    related: ["metric.net_input", "metric.cache_read", "metric.cache_creation", "metric.output", "calc.cost_math", "glossary.cache_5m_vs_1h"],
  },

  // ----- glossary -----
  {
    id: "column.pattern_type",
    category: "glossary",
    title: "Pattern types",
    oneLiner: "knowledge_snippet | command_pair | cross_tool_file | failure_correlation | session_summary.",
    detail: "`observer patterns` derives these from session activity. Each type has its own data shape; expect command_pair to carry {first, second}, knowledge_snippet to carry {topic, snippet}, and so on.",
  },
  {
    id: "glossary.action",
    category: "glossary",
    title: "Action",
    oneLiner: "One normalised tool call recorded by an adapter.",
    detail: "Action types are normalised across all adapters: read_file, write_file, edit_file, run_command, search_text, search_files, web_search, web_fetch, mcp_call, user_prompt, task_complete.",
  },
  {
    id: "glossary.api_turn",
    category: "glossary",
    title: "API turn",
    oneLiner: "One HTTP request captured by the local API proxy.",
    detail: "Records one row in `api_turns` per request, with the upstream usage envelope intact. The most accurate token source — see term.proxy_vs_jsonl for why.",
  },
  {
    id: "glossary.cache_5m_vs_1h",
    category: "glossary",
    title: "Cache 5m vs 1h tier",
    oneLiner: "Anthropic's prompt cache has two TTLs (5 minutes, 1 hour). The longer-lived tier costs 2× the short one to write.",
    detail: "When you set cache_control on a prompt block, Anthropic stores it in an ephemeral cache. By default the entry expires after ~5 minutes; setting `type: ephemeral, ttl: 3600` extends to 1 hour at 2× the write cost. Cache reads bill the same rate regardless of tier. The proxy records `cache_creation_1h_tokens` as the 1h-tier subset of `cache_creation_tokens`; the difference is the 5m-tier portion. Cost engine applies the right rate to each.",
    related: ["metric.cache_creation", "metric.cache_read", "calc.cost_math"],
  },
  {
    id: "glossary.compaction_events",
    category: "glossary",
    title: "Compaction events",
    oneLiner: "One row per /compact (or equivalent context-reset) recorded in the observer DB.",
    detail: "When Claude Code's `/compact` runs (or another tool's equivalent), the hook handler writes one row to `compaction_events` with a snapshot of every file the session had touched. The Reconcile pass later marks files NOT re-touched within the window as \"ghost files\" — content the model forgot about post-compact. v1.4.43+ adds the `injected_at` column populated by the D23 injector when post-compact recovery context is prepended to a request.",
    related: ["glossary.mechanism-compaction"],
  },
  {
    id: "glossary.compression_events",
    category: "glossary",
    title: "Compression events",
    oneLiner: "One row per individual compression decision recorded by the proxy pipeline.",
    detail: "When the proxy compresses a request body, two passes run: (1) per-content-type compressors rewrite individual tool_result blocks based on detected content type — json, code, logs, text, diff, html; (2) the budget enforcer drops low-importance messages and replaces them with markers. Each compress and each drop becomes one row in the compression_events table (migration 009) with mechanism / original_bytes / compressed_bytes / msg_index / importance_score. The aggregate columns on api_turns (compression_count, etc.) sum these per turn, but the events table is where you see the breakdown.",
    related: ["chart.compression_by_mechanism", "glossary.conversation_compression", "glossary.mechanism-drop"],
  },
  {
    id: "glossary.conversation_compression",
    category: "glossary",
    title: "Conversation compression",
    oneLiner: "Pre-forward compression of conversation payloads in the API proxy.",
    detail: "Compresses or drops large tool_result blocks before forwarding to the upstream API. Replaces dropped content with markers so the model still has a reference. Opt-in via `[compression.conversation].enabled` in observer config.",
    related: ["glossary.shell_compression", "glossary.marker"],
  },
  {
    id: "glossary.cost_provenance",
    category: "glossary",
    title: "How cost is calculated",
    oneLiner: "Cost is always computed locally from token_count × pricing_table[model]. Neither Anthropic nor OpenAI returns cost_usd in API responses, so we never have provider-billed ground truth from the proxy.",
    detail: "The pricing table source of truth lives in docs/pricing-reference.md (Anthropic + OpenAI + Gemini + others). Two adapters — OpenCode and Pi — capture cost client-side from the client's own usage envelope and write it into estimated_cost_usd; for those rows the cost engine uses the recorded value as-is. Every other path goes through tokens × rates. When a model isn't in the pricing table the engine falls back to the family prefix (claude-opus-4-7 inherits claude-opus-4 family rates); the Cost-tab Reliability column flags fallback rows with a \"~\" so you know the rate isn't exact-match.",
    related: ["column.cost.cost", "column.cost.reliab", "glossary.proxy_vs_jsonl"],
  },
  {
    id: "glossary.cross_platform_tool_calling",
    category: "glossary",
    title: "Cross-platform tool calling (MCP sharing)",
    oneLiner: "Every connected AI client can read every other client's recorded actions through the observer's 12-tool MCP server.",
    detail: "When `observer init` registers the MCP server with Claude Code, Cursor, and Codex, each client gains 12 tools that query the observer's unified database — not their own scoped slice. Concretely: when Cursor invokes `get_last_test_result`, the answer can be a `go test` run that Claude Code executed an hour earlier. When Codex calls `check_file_freshness(\"auth.ts\")`, the freshness signal reflects every adapter that touched the file. The 12 cross-querying MCP tools: check_file_freshness, get_file_history, get_session_summary, search_past_outputs, get_last_test_result, get_failure_context, get_action_details, check_command_freshness, get_session_recovery_context, get_project_patterns, get_cost_summary, get_redundancy_report. Two layers ship today: (1) read-side via MCP queries — any agent reads any other agent's recorded data; (2) write-side via patterns — `observer patterns` derives `cross_tool_file` patterns and `observer suggest` writes them into CLAUDE.md/AGENTS.md/.cursorrules so future sessions inherit. Not yet shipped: synthetic-tool-result injection (replaying agent A's tool execution into agent B's conversation context) — the MCP query model gives you the result on-demand instead.",
    related: ["glossary.tool", "column.pattern_type"],
  },
  {
    id: "glossary.freshness",
    category: "glossary",
    title: "Freshness state",
    oneLiner: "Per-read tag: fresh / stale / missing / modified-elsewhere / unknown.",
    detail: "Each file read gets one of these tags at write time by hashing the file content. fresh = first read in this session, OR re-read where the content matches the prior read. stale = re-read where the content differs from the prior read in the same session. missing = file no longer exists. modified-elsewhere = file changed between reads but by something other than an observable AI action. unknown = couldn't classify (e.g. permission denied at hash time). The stale-rereads metric only counts the stale tag, scoped per session.",
    related: ["calc.freshness_classification", "metric.stale_count"],
  },
  {
    id: "glossary.marker",
    category: "glossary",
    title: "Compression marker",
    oneLiner: "A placeholder message that tells the model \"something was dropped here\" without dumping the original content.",
    detail: "When the conversation-compression pipeline drops a message (importance score below threshold), it doesn't just delete the slot — that would shift indexes and confuse tool-call references. Instead it inserts a small marker like `[compressed: tool_result, 12.4 KB → 0 B]` so the model still sees a placeholder at that position. Marker count is what the compression panel surfaces.",
    related: ["glossary.conversation_compression", "metric.saved_bytes"],
  },
  {
    id: "glossary.mechanism-code",
    category: "glossary",
    title: "Mechanism: code",
    oneLiner: "Content-preserving source-code compressor — trims trailing whitespace, dedups identical runs, elides license banners, caps blank runs.",
    detail: "Four strict-content-preserving transforms applied to source-code tool_result bodies. Every non-comment, non-blank line of the input still appears bytewise in the output. The earlier (pre-v1.4.40) signature-only-skeleton design was retired after it caused a turn-count regression — the rewrite preserves bodies and only touches whitespace, run-length-duplicated lines, and a leading license banner.",
  },
  {
    id: "glossary.mechanism-compaction",
    category: "glossary",
    title: "Mechanism: compaction (D23)",
    oneLiner: "Post-compact context injection — proxy prepends a synthetic system block carrying recovery context after Claude Code's /compact resets the conversation.",
    detail: "Claude Code's `/compact` summarises the conversation and starts fresh — but the summary throws away tool-state (which files were read, which edits were made, which commands failed). The model has to re-discover the project on the first turn after `/compact`. D23 closes that gap: when the proxy sees an Anthropic request for a session with a recent `compaction_events` row, it prepends a synthetic system block with last 10 reads + last 5 edits + last 3 failures + top 5 learn rules. Cross-turn invariance is preserved via per-session caching — the prepended bytes are stable turn-over-turn.",
  },
  {
    id: "glossary.mechanism-diff",
    category: "glossary",
    title: "Mechanism: diff",
    oneLiner: "Unified-diff context stripper — keeps every change line + ±1 context line, drops the rest.",
    detail: "Strips unified-diff context lines beyond ±1 of each change. Keeps every header (`---`/`+++`/`@@`/index lines), every change line (`+` and `-`), and exactly one context line on each side of every change run. Drops everything else with a single `… N context lines elided` marker between runs.",
  },
  {
    id: "glossary.mechanism-drop",
    category: "glossary",
    title: "Mechanism: drop",
    oneLiner: "Low-importance message replaced by a marker — the only mechanism that loses content the model previously saw.",
    detail: "When per-content-type compression isn't enough to hit the target ratio, the budget enforcer ranks remaining messages by an importance score and drops the lowest-scored until the budget is met. Each drop is replaced by a marker block (a small placeholder text) so the conversation flow stays intact for the model, and the dropped content can still be retrieved on-demand via the `search_past_outputs` MCP tool.",
  },
  {
    id: "glossary.mechanism-html",
    category: "glossary",
    title: "Mechanism: html",
    oneLiner: "HTML cruft stripper — removes <script>, <style>, and HTML comments.",
    detail: "Strips `<script>...</script>` and `<style>...</style>` blocks (including their contents) and `<!-- ... -->` comments. Output remains valid HTML-ish enough for the model to read the visible structure without the weight of inline scripts or CSS.",
  },
  {
    id: "glossary.mechanism-json",
    category: "glossary",
    title: "Mechanism: json",
    oneLiner: "JSON value-erasure — replaces every scalar with a type sentinel while preserving structure.",
    detail: "Detects JSON content via parser sniffing, then replaces every scalar value (strings, numbers, booleans, nulls) with a sentinel naming its type (\"<string>\", \"<number>\", \"<bool>\", \"<null>\"). All structure (object keys, array nesting, depth) is preserved. The model still sees the JSON shape and can navigate it; only the actual data values disappear.",
  },
  {
    id: "glossary.mechanism-logs",
    category: "glossary",
    title: "Mechanism: logs",
    oneLiner: "Eight-pass log compressor — ANSI strip, CR collapse, PS-padding squash, progress-bar drop, dedup, blank-cap, then head+tail truncation with G32 level enrichment + E27 anomaly preservation.",
    detail: "Detects log-shaped content (timestamps, log-level prefixes, bracketed dates) and runs a strict-content-preserving pipeline before falling back to head+tail truncation. v1.4.40 added five content-preserving filters before the existing dedup pass; v1.4.41 enriched the truncation marker with log-level counts (G32); v1.4.43+ added anomaly lift-out (E27) so FATAL/ERROR/PANIC lines survive even when they would have landed in the elided middle.",
  },
  {
    id: "glossary.mechanism-read_cache",
    category: "glossary",
    title: "Mechanism: read_cache",
    oneLiner: "C16 per-call dedup of redundant Read tool_results — the second & subsequent identical Reads collapse to a marker.",
    detail: "When the model re-Reads a file with bytewise-identical content within the same Anthropic request body, the second and subsequent occurrences of the Read tool_result are replaced inline with a deterministic marker `[file <path> unchanged since earlier in this turn; same content already returned]`. Anthropic includes the entire conversation history every turn, so when the model re-Reads a file in turn N+1, both turn N's and turn N+1's Read tool_results appear in the same request — per-call dedup catches it without any external state.",
  },
  {
    id: "glossary.mechanism-rolling_summary",
    category: "glossary",
    title: "Mechanism: rolling_summary",
    oneLiner: "D20 rolling summarisation — older messages collapse into a one-paragraph synthetic marker when the conversation crosses a token threshold.",
    detail: "When a session's conversation byte-count crosses `compression.conversation.rolling.threshold_tokens` (default 80000), the proxy calls Anthropic with the user's captured Authorization (or x-api-key) to get a one-paragraph summary of older messages, then replaces those messages inline with a `[<N> earlier messages summarized: <text>]` marker. Per-session sticky boundary preserves cross-turn invariance — turn N+1 reuses turn N's summary + boundary unless the unsummarised tail grows past `2 × PreserveLastN` messages.",
  },
  {
    id: "glossary.mechanism-stash",
    category: "glossary",
    title: "Mechanism: stash (CCR)",
    oneLiner: "Compressed Content Retrieval — large tool_result bodies are written to a content-addressed disk stash and replaced inline with a marker pointing at the SHA.",
    detail: "Tool_result bodies whose post-per-type-compression size still exceeds the inline threshold (default 8 KB) are written to `~/.observer/stash/<sha256>` and replaced inline with `[output <N>KB stashed at observer://stash/<sha>; use retrieve_stashed]`. The model retrieves originals on-demand via the `retrieve_stashed` MCP tool, which validates the on-disk bytes re-hash to the requested SHA before returning them.",
  },
  {
    id: "glossary.mechanism-text",
    category: "glossary",
    title: "Mechanism: text",
    oneLiner: "Plain-text head+tail truncation — fallback for content not matched by other mechanisms.",
    detail: "The catch-all compressor for content that didn't classify as code/json/logs/diff/html. Applies head+tail truncation: keeps the first 40 + last 40 lines for any input over 80 lines, with an elision marker in the middle. Short outputs pass through unchanged.",
  },
  {
    id: "glossary.mechanism-tools",
    category: "glossary",
    title: "Mechanism: tools",
    oneLiner: "Tool/function schema compression — strips deep `examples` keys and trims long tool descriptions to first 2 paragraphs.",
    detail: "Anthropic request bodies carry the full ~94KB tools array on every cache-cold turn (Claude Code SDK ships ~45 tools). Two strict transforms shrink it: top-level `description` trim (when ≥3 paragraphs, keep first 2) and deep `examples` strip from `input_schema` (recursive). Forbidden: never touches tool `name`, `input_schema.type`, `properties` keys, nested `type`/`description`/`required`/`enum`/`minimum`/`maximum`. Touching parameter schemas changes the model's tool-use behaviour — the v1.4.38 turn-count regression class.",
  },
  {
    id: "glossary.project",
    category: "glossary",
    title: "Project",
    oneLiner: "A working-directory root that owns sessions and actions.",
    detail: "Derived from the cwd at session start. Paths inside a `.git/worktrees/...` manager directory are folded back to the working-tree root.",
  },
  {
    id: "glossary.proxy_vs_jsonl",
    category: "glossary",
    title: "Proxy vs JSONL",
    oneLiner: "Two ways the observer captures what your AI client did. Proxy = ground truth, JSONL = best-effort log parsing.",
    detail: "PROXY: a localhost HTTP server (default 127.0.0.1:8820) that sits between your AI client and the upstream API. Every request flows through it, so the observer sees exact request bodies, response usage envelopes, and timings — one api_turns row per HTTP call, no dedup needed. JSONL: the AI client (Claude Code, Codex, …) writes every conversation to a JSONL log on disk; the observer's file watcher parses these into token_usage rows. Plentiful but noisy — the clients echo cumulative usage on every content block of a multi-block response, so a single API call can write 2-4 rows the cost engine has to dedupe.",
    related: ["column.cost.source", "tile.api_turns", "tile.token_rows", "calc.dedup_a1"],
  },
  {
    id: "glossary.session",
    category: "glossary",
    title: "Session",
    oneLiner: "One continuous AI-coding conversation in a single tool, scoped to a single working directory.",
    detail: "Each session has a stable ID (claude-code's session UUID, codex's rollout ID, etc.) and lives in the `sessions` table. All actions, token rows, and api_turns associated with a session reference its ID.",
  },
  {
    id: "glossary.shell_compression",
    category: "glossary",
    title: "Shell-output compression",
    oneLiner: "Trimming shell command output BEFORE it gets recorded to the AI client's context.",
    detail: "Different from conversation compression — runs upstream of recording. When the AI client invokes a Bash hook through the observer, declarative filters (git, go test, docker, kubectl, cargo, pytest, npm, gradle, go build, …) strip routine noise (compilation status banners, dependency-resolution chatter, retry messages) before the output is recorded as the tool_result. Always on for any of the bundled command families; opt-in for new commands via [compression.shell.filters] in observer config.",
    related: ["glossary.conversation_compression"],
  },
  {
    id: "glossary.sidechain",
    category: "glossary",
    title: "Sidechain (sub-agent activity)",
    oneLiner: "Tool calls emitted inside a sub-agent runtime — parent session's Agent tool spawned them.",
    detail: "When the main agent calls Claude Code's `Agent` tool with a `prompt` and `subagent_type`, Claude Code spawns a fresh sub-agent runtime that executes the prompt independently. Every line that runtime emits gets `isSidechain: true` in the JSONL log; the observer's adapter copies that flag onto the actions table's `is_sidechain` column. Crucially, sub-agents share the parent's session_id — they're NOT separate sessions. The is_sidechain flag is the only structural marker distinguishing parent-thread work from sub-agent work.",
    related: ["column.sessions.sidechain", "metric.stale_count", "column.discover.stale"],
  },
  {
    id: "glossary.token_row",
    category: "glossary",
    title: "Token row",
    oneLiner: "One token-usage event recovered by parsing the AI client's JSONL session log.",
    detail: "Plentiful but unreliable — clients echo cumulative usage on every content block, which the cost engine has to dedupe. See calc.dedup_a1.",
  },
  {
    id: "glossary.tool",
    category: "glossary",
    title: "Tool (AI client)",
    oneLiner: "The AI coding client that produced an action.",
    detail: "In this dashboard \"tool\" means the *client* (claude-code, cursor, codex, cline, copilot), not the per-message tool name (read_file, run_command). The latter is \"Tool name\" on the Actions tab.",
  },
];
const BY_ID = new Map(HELP_REGISTRY.map((e) => [e.id, e]));

export function getHelp(id: string | null | undefined): HelpEntry | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

export function helpByCategory(): Record<HelpCategory, HelpEntry[]> {
  const out: Record<HelpCategory, HelpEntry[]> = {
    tab: [],
    tile: [],
    chart: [],
    column: [],
    filter: [],
    metric: [],
    calc: [],
    glossary: [],
  };
  for (const e of HELP_REGISTRY) out[e.category].push(e);
  return out;
}
