// Unit tests for the pure helpers in src/binary-internals.ts.
//
// Kept separate from src/binary.ts so we don't need a `vscode`
// runtime shim — `vscode` is only imported by binary.ts itself, and
// resolveBinary / downloadFromReleases are exercised manually in the
// Extension Development Host (M0 acceptance §4 of the plan).

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import {
  PLATFORM_TO_ASSET,
  exeName,
  parseSha256Sums,
  which,
  fileExists,
} from '../../src/binary-internals';

describe('parseSha256Sums', () => {
  const sample = [
    '# generated by sha256sum',
    '',
    '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef  observer-v1.7.26-linux-x64.tar.gz',
    'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210  observer-v1.7.26-darwin-arm64.tar.gz',
    'aaaabbbbccccddddeeeeffff0000111122223333444455556666777788889999 *observer-v1.7.26-win32-x64.zip',
    '',
  ].join('\n');

  test('extracts hash for an existing filename', () => {
    assert.equal(
      parseSha256Sums(sample, 'observer-v1.7.26-linux-x64.tar.gz'),
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    );
  });

  test('matches the asterisk-prefix (binary mode) format', () => {
    assert.equal(
      parseSha256Sums(sample, 'observer-v1.7.26-win32-x64.zip'),
      'aaaabbbbccccddddeeeeffff0000111122223333444455556666777788889999',
    );
  });

  test('returns undefined for a missing filename', () => {
    assert.equal(parseSha256Sums(sample, 'nonexistent.tar.gz'), undefined);
  });

  test('skips comments and blank lines', () => {
    const noisy = '# header\n\n# another comment\n';
    assert.equal(parseSha256Sums(noisy, 'whatever.tar.gz'), undefined);
  });

  test('handles CRLF line endings (Windows SHA256SUMS)', () => {
    const crlf = sample.replace(/\n/g, '\r\n');
    assert.equal(
      parseSha256Sums(crlf, 'observer-v1.7.26-darwin-arm64.tar.gz'),
      'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210',
    );
  });

  test('lowercases mixed-case hex from the input', () => {
    const upper =
      '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF  archive.tar.gz';
    assert.equal(
      parseSha256Sums(upper, 'archive.tar.gz'),
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
    );
  });
});

describe('PLATFORM_TO_ASSET', () => {
  test('covers the five matrix-built platforms', () => {
    const expected = new Set([
      'linux-x64',
      'linux-arm64',
      'darwin-x64',
      'darwin-arm64',
      'win32-x64',
    ]);
    assert.deepEqual(new Set(Object.keys(PLATFORM_TO_ASSET)), expected);
  });

  test('asset name equals the key (no aliasing)', () => {
    for (const [k, v] of Object.entries(PLATFORM_TO_ASSET)) {
      assert.equal(k, v, `expected ${k} to map to itself`);
    }
  });
});

describe('exeName', () => {
  test('matches the host platform', () => {
    assert.equal(
      exeName(),
      process.platform === 'win32' ? 'observer.exe' : 'observer',
    );
  });
});

describe('which', () => {
  test('returns undefined when PATH is empty', async () => {
    assert.equal(await which('observer', { PATH: '' }), undefined);
  });

  test('returns undefined when the command is not on any PATH dir', async () => {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      assert.equal(await which('definitely-not-on-path', { PATH: tmp }), undefined);
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });

  test('finds an executable in a PATH directory', async () => {
    if (process.platform === 'win32') return; // skip — PATHEXT path covered separately
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      const target = path.join(tmp, 'fake-observer');
      await fs.writeFile(target, '#!/bin/sh\necho hi\n', { mode: 0o755 });
      const found = await which('fake-observer', { PATH: tmp });
      assert.equal(found, target);
      assert.ok(await fileExists(found!));
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });

  test('skips empty PATH segments', async () => {
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'observer-which-'));
    try {
      const target = path.join(tmp, 'tool');
      await fs.writeFile(target, '#!/bin/sh\n', { mode: 0o755 });
      // Empty segments around the real dir; `which` should not crash.
      const PATH = [`${path.delimiter}`, tmp, ''].join(path.delimiter);
      const found = await which('tool', { PATH });
      assert.equal(found, target);
    } finally {
      await fs.rm(tmp, { recursive: true, force: true });
    }
  });
});
