#!/usr/bin/env bash
# ab-codex-setup.sh — provision a clean Codex CLI A/B compression
# test environment. Mirrors ab-claude-setup.sh on the OpenAI side.
#
# Layout:
#   /tmp/ab-codex/
#     on/    — observer config + DB + cloned repo (compression ON)
#     off/   — observer config + DB + cloned repo (compression OFF)
#
# Two observer daemons run in parallel: ON on port 8832, OFF on
# port 8833. Each writes to its own SQLite DB so post-run extraction
# is a clean diff.
#
# Defaults to expressjs/express but accepts $REPO_URL override:
#   REPO_URL=https://github.com/koajs/koa.git ./scripts/ab-codex-setup.sh
#
# Re-running wipes /tmp/ab-codex/ first — pass --keep to preserve.
# Daemons are NOT started here; this script is just the filesystem
# setup. Use scripts/ab-codex-start.sh to bring them up.
#
# Companion scripts:
#   scripts/ab-codex-start.sh   — start both daemons
#   scripts/ab-codex-stop.sh    — stop both daemons
#   scripts/ab-codex-report.sh  — diff DBs and print results
#
# Note on auth: codex needs OPENAI_API_KEY in your environment OR a
# `codex login` session. The launcher (`observer codex`) doesn't
# manage credentials — it just routes via the proxy. Pre-flight in
# ab-codex-start.sh verifies the proxy reaches api.openai.com via
# a fake key (expects 401); to verify your real key works run a
# single `codex exec "hi"` against either side's repo.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/expressjs/express.git}"
ROOT="${AB_CODEX_ROOT:-/tmp/ab-codex}"
KEEP=0
for arg in "$@"; do
  case "$arg" in
    --keep) KEEP=1 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -d "$ROOT" && $KEEP -eq 0 ]]; then
  echo "removing $ROOT (pass --keep to preserve)" >&2
  rm -rf "$ROOT"
fi
mkdir -p "$ROOT/on" "$ROOT/off"

TMP_CLONE="$ROOT/.clone-source"
if [[ ! -d "$TMP_CLONE" ]]; then
  echo "cloning $REPO_URL → $TMP_CLONE" >&2
  git clone --depth 1 "$REPO_URL" "$TMP_CLONE"
fi
for side in on off; do
  if [[ ! -d "$ROOT/$side/repo" ]]; then
    echo "copying clone → $ROOT/$side/repo" >&2
    cp -a "$TMP_CLONE" "$ROOT/$side/repo"
    rm -rf "$ROOT/$side/repo/.git"
  fi
done

write_config() {
  local side=$1   # on | off
  local port=$2   # 8832 or 8833
  local enabled=$3 # true or false
  local cfg="$ROOT/$side/observer-config.toml"
  cat > "$cfg" <<TOML
# Observer config for the codex A/B compression test ($side side).
# Generated by scripts/ab-codex-setup.sh — edit at your own risk;
# rerunning the setup script overwrites it.

[observer]
  db_path = "$ROOT/$side/observer.db"
  log_level = "info"
  [observer.watch]
    enabled_adapters = []
  [observer.freshness]
    enable_content_hashing = false
  [observer.secrets]
    enable_scrubbing = true
  [observer.retention]
    max_age_days = 180
    prune_on_startup = false

[proxy]
  enabled = true
  port = $port
  anthropic_upstream = "https://api.anthropic.com"
  openai_upstream = "https://api.openai.com"
  chatgpt_upstream = "https://chatgpt.com"
  # Reject chatgpt-auth WebSocket upgrades so codex falls straight to its
  # HTTPS transport. Without this, codex's WebSocket attempts canonically
  # take ~2 minutes (7 retries × ~15s) to time out before it falls back —
  # which adds dead time to every codex session start. The flag has no
  # effect on Anthropic or sk-OpenAI traffic.
  force_chatgpt_http = true

[compression]
  [compression.shell]
    enabled = false
  [compression.indexing]
    enabled = false
  [compression.conversation]
    enabled = $enabled
    mode = "token"
    target_ratio = 0.5
    preserve_last_n = 5
    compress_types = ["json", "logs", "text", "code"]
    [compression.conversation.stash]
      enabled = $enabled
      dir = "$ROOT/$side/stash"
      threshold_bytes = 8192
      max_total_mb = 256
    [compression.conversation.rolling]
      enabled = false
      threshold_tokens = 80000
      summary_model = "claude-haiku-4-5"
      openai_summary_model = "gpt-5-nano"
      auth_cache_size = 1024

[intelligence]
  monthly_budget_usd = 0.0
TOML
  echo "wrote $cfg" >&2
}

write_config on  8832 true
write_config off 8833 false

cat <<EOF

Codex A/B environment ready at $ROOT.

  ON  side:  $ROOT/on/repo            → proxy 127.0.0.1:8832, compression=true
  OFF side:  $ROOT/off/repo           → proxy 127.0.0.1:8833, compression=false

Next steps:
  1. Start both daemons:    ./scripts/ab-codex-start.sh
  2. In terminal A:         cd $ROOT/on/repo && \\
                              observer codex --proxy http://127.0.0.1:8832
  3. In terminal B:         cd $ROOT/off/repo && \\
                              observer codex --proxy http://127.0.0.1:8833
  4. Run the same prompts in both, then:
                            ./scripts/ab-codex-report.sh

Auth: codex needs OPENAI_API_KEY exported OR a prior \`codex login\`.
The launcher just routes — it doesn't manage credentials. Both auth
shapes (sk- API key + Bearer eyJ JWT for ChatGPT-Plus) flow through
the same proxy override; the proxy detects the bearer shape and
path-translates to chatgpt.com when needed.

Prompt list (run all four in each session):
  1. "Walk through the codebase and summarize the architecture in 3 paragraphs."
  2. "What are the top 5 public APIs? Include file:line for each."
  3. "Trace how a request flows from app.use() through to the handler."
  4. "Find the test for app.set() and explain the assertions."
EOF
