#!/usr/bin/env bash
# ab-claude-setup.sh — provision a clean Claude Code A/B compression
# test environment.
#
# Layout:
#   /tmp/ab-claude/
#     on/    — observer config + DB + cloned repo (compression ON)
#     off/   — observer config + DB + cloned repo (compression OFF)
#
# Two observer daemons run in parallel: ON on port 8830, OFF on
# port 8831. Each writes to its own SQLite DB so post-run extraction
# is a clean diff.
#
# Defaults to expressjs/express but accepts $REPO_URL override:
#   REPO_URL=https://github.com/koajs/koa.git ./scripts/ab-claude-setup.sh
#
# Re-running wipes /tmp/ab-claude/ first — pass --keep to preserve.
# Daemons are NOT started here; this script is just the filesystem
# setup. Use scripts/ab-claude-start.sh to bring them up.
#
# Companion scripts:
#   scripts/ab-claude-start.sh   — start both daemons
#   scripts/ab-claude-stop.sh    — stop both daemons
#   scripts/ab-claude-report.sh  — diff DBs and print results

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/expressjs/express.git}"
ROOT="${AB_CLAUDE_ROOT:-/tmp/ab-claude}"
KEEP=0
for arg in "$@"; do
  case "$arg" in
    --keep) KEEP=1 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -d "$ROOT" && $KEEP -eq 0 ]]; then
  echo "removing $ROOT (pass --keep to preserve)" >&2
  rm -rf "$ROOT"
fi
mkdir -p "$ROOT/on" "$ROOT/off"

# Clone the repo once, then copy into both folders. Faster than two
# git clones and guarantees byte-identical working trees.
TMP_CLONE="$ROOT/.clone-source"
if [[ ! -d "$TMP_CLONE" ]]; then
  echo "cloning $REPO_URL → $TMP_CLONE" >&2
  git clone --depth 1 "$REPO_URL" "$TMP_CLONE"
fi
for side in on off; do
  if [[ ! -d "$ROOT/$side/repo" ]]; then
    echo "copying clone → $ROOT/$side/repo" >&2
    cp -a "$TMP_CLONE" "$ROOT/$side/repo"
    rm -rf "$ROOT/$side/repo/.git"
  fi
done

write_config() {
  local side=$1   # on | off
  local port=$2   # 8830 or 8831
  local enabled=$3 # true or false
  local cfg="$ROOT/$side/observer-config.toml"
  cat > "$cfg" <<TOML
# Observer config for the A/B compression test ($side side).
# Generated by scripts/ab-claude-setup.sh — edit at your own risk;
# rerunning the setup script overwrites it.

[observer]
  db_path = "$ROOT/$side/observer.db"
  log_level = "info"
  [observer.watch]
    # Disable adapters: this install only proxies Claude Code.
    # Skipping watch keeps the A/B environment from picking up the
    # main \$HOME's session files and polluting the DB.
    enabled_adapters = []
  [observer.freshness]
    enable_content_hashing = false
  [observer.secrets]
    enable_scrubbing = true
  [observer.retention]
    max_age_days = 180
    prune_on_startup = false

[proxy]
  enabled = true
  port = $port
  anthropic_upstream = "https://api.anthropic.com"
  openai_upstream = "https://api.openai.com"

[compression]
  [compression.shell]
    enabled = false
  [compression.indexing]
    enabled = false
  [compression.conversation]
    enabled = $enabled
    mode = "token"
    target_ratio = 0.5
    preserve_last_n = 5
    compress_types = ["json", "logs", "text"]

[intelligence]
  monthly_budget_usd = 0.0
TOML
  echo "wrote $cfg" >&2
}

write_config on  8830 true
write_config off 8831 false

cat <<EOF

A/B environment ready at $ROOT.

  ON  side:  $ROOT/on/repo            → proxy 127.0.0.1:8830, compression=true
  OFF side:  $ROOT/off/repo           → proxy 127.0.0.1:8831, compression=false

Next steps:
  1. Start both daemons:    ./scripts/ab-claude-start.sh
  2. In terminal A:         ANTHROPIC_BASE_URL=http://127.0.0.1:8830 \\
                              cd $ROOT/on/repo && claude
  3. In terminal B:         ANTHROPIC_BASE_URL=http://127.0.0.1:8831 \\
                              cd $ROOT/off/repo && claude
  4. Run the same prompts in both, then:
                            ./scripts/ab-claude-report.sh

Prompt list (run all four in each session):
  1. "Walk through the codebase and summarize the architecture in 3 paragraphs."
  2. "What are the top 5 public APIs? Include file:line for each."
  3. "Trace how a request flows from app.use() through to the handler."
  4. "Find the test for app.set() and explain the assertions."
EOF
