package learn

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// ManagedBlockStart / End bracket the section that `observer learn --apply`
// rewrites. Hand-authored content above or below the block is preserved.
const (
	ManagedBlockStart = "<!-- sbso:learn-rules:start -->"
	ManagedBlockEnd   = "<!-- sbso:learn-rules:end -->"
)

// RenderMarkdown returns the managed-block body (no outer markers) that
// lists rules as markdown bullets. Safe to embed in CLAUDE.md or AGENTS.md.
func RenderMarkdown(rules []Rule, now time.Time) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "## Known command corrections\n\n")
	fmt.Fprintf(&b, "_Auto-generated by `observer learn` on %s. Edits outside the markers above/below are preserved._\n\n",
		now.UTC().Format("2006-01-02"))
	if len(rules) == 0 {
		fmt.Fprintf(&b, "_No recovery patterns observed yet — keep working and re-run to refresh._\n")
		return b.String()
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "- **`%s`** (%s, %d failure(s), %d recovered)\n",
			oneLine(r.CommandSummary), defaultIf(r.ErrorCategory, "uncategorized"),
			r.FailureCount, r.RecoveryCount)
		if len(r.EditedFiles) > 0 {
			fmt.Fprintf(&b, "  - Previously fixed by editing: %s\n",
				strings.Join(quote(r.EditedFiles), ", "))
		}
		if msg := oneLine(r.ErrorMessage); msg != "" {
			fmt.Fprintf(&b, "  - Last failure: %s\n", truncate(msg, 160))
		}
	}
	return b.String()
}

// RenderCursorRules produces a compact .cursorrules body — .cursorrules is
// plain text, so we drop Markdown decoration.
func RenderCursorRules(rules []Rule, now time.Time) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# sbso:learn-rules — generated %s\n",
		now.UTC().Format("2006-01-02"))
	if len(rules) == 0 {
		fmt.Fprintf(&b, "# (no recovery patterns observed yet)\n")
		return b.String()
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "- Command `%s` (%s, x%d): previously fixed by editing %s\n",
			oneLine(r.CommandSummary), defaultIf(r.ErrorCategory, "?"),
			r.FailureCount, strings.Join(quote(r.EditedFiles), ", "))
	}
	return b.String()
}

// Apply rewrites the managed block in the target file. If the block is
// missing the body is appended to the end of the file (creating the file
// if needed). Idempotent — applying the same body twice leaves the file
// byte-for-byte identical.
func Apply(path string, body string) (changed bool, err error) {
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
	case os.IsNotExist(err):
		existing = nil
	default:
		return false, fmt.Errorf("learn.Apply read %s: %w", path, err)
	}
	updated := rewrite(existing, body)
	if bytes.Equal(existing, updated) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("learn.Apply mkdir: %w", err)
	}
	if err := os.WriteFile(path, updated, 0o644); err != nil {
		return false, fmt.Errorf("learn.Apply write %s: %w", path, err)
	}
	return true, nil
}

// rewrite returns existing with the managed block replaced (or appended)
// containing body. Extracted so tests can exercise the byte logic without
// filesystem round-trips.
func rewrite(existing []byte, body string) []byte {
	block := ManagedBlockStart + "\n" + body + "\n" + ManagedBlockEnd

	startIdx := bytes.Index(existing, []byte(ManagedBlockStart))
	endIdx := bytes.Index(existing, []byte(ManagedBlockEnd))

	var head, tail []byte
	if startIdx >= 0 && endIdx > startIdx {
		head = bytes.TrimRight(existing[:startIdx], "\n")
		endOfBlock := endIdx + len(ManagedBlockEnd)
		tail = bytes.TrimLeft(existing[endOfBlock:], "\n")
	} else {
		head = bytes.TrimRight(existing, "\n")
		tail = nil
	}

	var out []byte
	if len(head) > 0 {
		out = append(out, head...)
		out = append(out, '\n', '\n')
	}
	out = append(out, []byte(block)...)
	out = append(out, '\n')
	if len(tail) > 0 {
		out = append(out, '\n')
		out = append(out, tail...)
		if !bytes.HasSuffix(out, []byte("\n")) {
			out = append(out, '\n')
		}
	}
	return out
}

// Diff returns a unified-style preview of applying body to path. Exposed so
// the CLI's default dry-run can show what --apply would change.
func Diff(path string, body string) (string, error) {
	var existing []byte
	if b, err := os.ReadFile(path); err == nil {
		existing = b
	} else if !os.IsNotExist(err) {
		return "", err
	}
	updated := rewrite(existing, body)
	var out bytes.Buffer
	fmt.Fprintf(&out, "--- %s\n+++ %s (after --apply)\n", path, path)
	writeSnippet(&out, existing, updated)
	return out.String(), nil
}

func writeSnippet(w io.Writer, before, after []byte) {
	// Naive unified-ish preview: all "before" lines as '-', all "after"
	// lines as '+'. Fine for small managed blocks — callers just want to
	// see what will change.
	for _, l := range splitLines(before) {
		fmt.Fprintf(w, "- %s\n", l)
	}
	for _, l := range splitLines(after) {
		fmt.Fprintf(w, "+ %s\n", l)
	}
}

func splitLines(b []byte) []string {
	if len(b) == 0 {
		return nil
	}
	parts := bytes.Split(b, []byte("\n"))
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		out = append(out, string(p))
	}
	if len(out) > 0 && out[len(out)-1] == "" {
		out = out[:len(out)-1]
	}
	return out
}

func oneLine(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return s
}

func defaultIf(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

func quote(xs []string) []string {
	out := make([]string, 0, len(xs))
	for _, x := range xs {
		out = append(out, "`"+x+"`")
	}
	return out
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-1] + "…"
}
